version: '3'

services:
  mongodb:
    image: mongo:7.0.2
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

  my-redis:
    image: redis:7.2.1
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    image: nikitakvl/url-shortener.app
    container_name: URL-shortener
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - my-redis
    networks:
      - app-network

networks:
  app-network:
